# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'komakiProject.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtWidgets, uic
from PyQt5.QtCore import Qt,QTimer
from PyQt5.QtWidgets import QFileDialog,QMessageBox
from komaki import Komaki as komaki_core
from PyQt5.QtGui import QIcon
import os
import json


class Ui_Komaki(object):
    
    def setupUi(self, Komaki):
        Komaki.setObjectName("Komaki")
        Komaki.resize(463, 573)
        Komaki.setWindowIcon(QIcon("k_icon.png"))
        self.select_file = QtWidgets.QPushButton(Komaki)
        self.select_file.setGeometry(QtCore.QRect(280, 30, 75, 23))
        self.select_file.setObjectName("select_file")
        #my changes
        # central_widget = QWidget()
        # self.setCentralWidget(central_widget)
        # layout = QVBoxLayout(central_widget)
        # layout.addWidget(self.select_file)
        #my changes
        self.label = QtWidgets.QLabel(Komaki)
        self.label.setGeometry(QtCore.QRect(50, 10, 61, 16))
        self.label.setObjectName("label")
        self.generate = QtWidgets.QPushButton(Komaki)
        self.generate.setGeometry(QtCore.QRect(160, 530, 75, 23))
        self.generate.setObjectName("generate")
        self.label_2 = QtWidgets.QLabel(Komaki)
        self.label_2.setGeometry(QtCore.QRect(50, 280, 71, 16))
        self.label_2.setObjectName("label_2")
        self.word_radio = QtWidgets.QRadioButton(Komaki)
        self.word_radio.setGeometry(QtCore.QRect(60, 320, 82, 17))
        self.word_radio.setCheckable(True)
        self.word_radio.setChecked(True)
        self.word_radio.setObjectName("word_radio")
        self.pdf_radio = QtWidgets.QRadioButton(Komaki)
        self.pdf_radio.setGeometry(QtCore.QRect(230, 320, 82, 17))
        self.pdf_radio.setObjectName("pdf_radio")
        self.Main_bar = QtWidgets.QProgressBar(Komaki)
        self.Main_bar.setGeometry(QtCore.QRect(50, 490, 331, 23))
        self.Main_bar.setProperty("value", 0)
        self.Main_bar.setObjectName("Main_bar")
        self.label_3 = QtWidgets.QLabel(Komaki)
        self.label_3.setGeometry(QtCore.QRect(50, 80, 131, 16))
        self.label_3.setObjectName("label_3")
        self.file_name = QtWidgets.QLineEdit(Komaki)
        self.file_name.setGeometry(QtCore.QRect(50, 30, 221, 20))
        self.file_name.setObjectName("file_name")
        self.CEFR_bar = QtWidgets.QProgressBar(Komaki)
        self.CEFR_bar.setGeometry(QtCore.QRect(60, 150, 331, 23))
        self.CEFR_bar.setProperty("value", 0)
        self.CEFR_bar.setObjectName("CEFR_bar")
        self.find = QtWidgets.QPushButton(Komaki)
        self.find.setGeometry(QtCore.QRect(160, 180, 75, 23))
        self.find.setObjectName("find")
        self.label_4 = QtWidgets.QLabel(Komaki)
        self.label_4.setGeometry(QtCore.QRect(100, 110, 61, 16))
        self.label_4.setObjectName("label_4")
        self.cefr_level = QtWidgets.QLineEdit(Komaki)
        self.cefr_level.setGeometry(QtCore.QRect(160, 110, 61, 20))
        self.cefr_level.setText("")
        self.cefr_level.setReadOnly(True)
        self.cefr_level.setObjectName("cefr_level")
        self.label_5 = QtWidgets.QLabel(Komaki)
        self.label_5.setGeometry(QtCore.QRect(50, 240, 171, 16))
        self.label_5.setObjectName("label_5")
        self.comboBox = QtWidgets.QComboBox(Komaki)
        self.comboBox.setGeometry(QtCore.QRect(210, 240, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_6 = QtWidgets.QLabel(Komaki)
        self.label_6.setGeometry(QtCore.QRect(50, 220, 101, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Komaki)
        self.label_7.setGeometry(QtCore.QRect(50, 60, 101, 16))
        self.label_7.setObjectName("label_7")
        self.footer_font = QtWidgets.QSpinBox(Komaki)
        self.footer_font.setGeometry(QtCore.QRect(320, 350, 42, 22))
        self.footer_font.setProperty("value", 7)
        self.footer_font.setObjectName("footer_font")
        self.label_8 = QtWidgets.QLabel(Komaki)
        self.label_8.setGeometry(QtCore.QRect(260, 350, 61, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Komaki)
        self.label_9.setGeometry(QtCore.QRect(260, 392, 47, 21))
        self.label_9.setObjectName("label_9")
        self.margin = QtWidgets.QSpinBox(Komaki)
        self.margin.setGeometry(QtCore.QRect(320, 390, 42, 22))
        self.margin.setProperty("value", 20)
        self.margin.setObjectName("margin")
        self.scale_factor_1 = QtWidgets.QSpinBox(Komaki)
        self.scale_factor_1.setGeometry(QtCore.QRect(320, 430, 42, 22))
        self.scale_factor_1.setProperty("value", 7)
        self.scale_factor_1.setObjectName("scale_factor_1")
        self.label_10 = QtWidgets.QLabel(Komaki)
        self.label_10.setGeometry(QtCore.QRect(370, 430, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.scale_factor_2 = QtWidgets.QSpinBox(Komaki)
        self.scale_factor_2.setGeometry(QtCore.QRect(390, 430, 42, 22))
        self.scale_factor_2.setProperty("value", 8)
        self.scale_factor_2.setObjectName("scale_factor_2")
        self.label_11 = QtWidgets.QLabel(Komaki)
        self.label_11.setGeometry(QtCore.QRect(260, 430, 61, 20))
        self.label_11.setObjectName("label_11")

        self.retranslateUi(Komaki)
        QtCore.QMetaObject.connectSlotsByName(Komaki)

    def retranslateUi(self, Komaki):
        _translate = QtCore.QCoreApplication.translate
        Komaki.setWindowTitle(_translate("Komaki", "Komaki Project"))
        self.select_file.setText(_translate("Komaki", "Select file"))
        self.label.setText(_translate("Komaki", "File location (select a pdf file)"))
        self.generate.setText(_translate("Komaki", "Generate"))
        self.label_2.setText(_translate("Komaki", "Output file"))
        self.word_radio.setText(_translate("Komaki", "Word file"))
        self.pdf_radio.setText(_translate("Komaki", "PDF file"))
        self.label_3.setText(_translate("Komaki", "Find texts CEFR level"))
        self.find.setText(_translate("Komaki", "Find"))
        self.label_4.setText(_translate("Komaki", "CEFR level:"))
        self.label_5.setText(_translate("Komaki", "Translate words from C2 level to"))
        self.comboBox.setItemText(0, _translate("Komaki", "C1"))
        self.comboBox.setItemText(1, _translate("Komaki", "B2"))
        self.comboBox.setItemText(2, _translate("Komaki", "B1"))
        self.comboBox.setItemText(3, _translate("Komaki", "A2"))
        self.label_6.setText(_translate("Komaki", "_______"))
        self.label_7.setText(_translate("Komaki", "_______"))
        self.label_8.setText(_translate("Komaki", "Footer font"))
        self.label_9.setText(_translate("Komaki", "Margin"))
        self.label_10.setText(_translate("Komaki", "/"))
        self.label_11.setText(_translate("Komaki", "Scale factor"))
        #my changes
        # self.file_name.acceptDrops(True)
        self.select_file.clicked.connect(self.open_file_dialog)
        self.find.clicked.connect(self.checks_cefr_level)
        self.generate.clicked.connect(self.generate_button)
    
    def open_file_dialog(self):
        # Open file dialog
        file_path, _ = QFileDialog.getOpenFileName(
            self.select_file,
            "Select a file",
            "",  # Starting directory (empty = current directory)
            "PDF Files (*.pdf)"  # File filters
        )
        
        # Check if a file was selected
        if file_path:
            print(f"Selected file: {file_path}")
            self.file_name.setText(file_path)
            # You can store the file path in a variable or process it further
            self.selected_file_path = file_path
            # self.komaki_core = komaki_core(self.file_name.text)
        else:
            print("No file selected")
    
    # def checks_cefr_level(self):
    #     self.komaki_core = komaki_core(self.file_name.text())
    #     self.cefr_level.setText("wait...")
    #     self.cefr_level_text = str(self.komaki_core.get_CEFR_level()[1])
    #     print(self.cefr_level_text)
    #     self.cefr_level.setText(self.cefr_level_text)
    def checks_cefr_level(self):
        self.cefr_level.setText("wait...")
        
        QTimer.singleShot(10, self.run_cefr_check)

    def run_cefr_check(self):
        self.komaki_core = komaki_core(self.file_name.text())
        self.cefr_level_text = str(self.komaki_core.get_CEFR_level()[1])
        # print(self.cefr_level_text)
        self.cefr_level.setText(self.cefr_level_text)
        self.CEFR_bar.setValue(100)
    
    def generate_button(self):
        self.komaki_core = komaki_core(self.file_name.text())
        desired_level = self.comboBox.currentText()
        level_dict = {"C1":4,"B2":3,"B1":2,"A2":1}
        desired_level_num = level_dict[desired_level]
        # file_full_name = os.path.basename(self.file_name.text())
        file_full_name = self.komaki_core.file_full_name
        # file_name = os.path.splitext(file_full_name)[0]
        file_name = self.komaki_core.file_name_only
        # folder = os.path.dirname(self.file_name.text())
        folder = self.komaki_core.dir
        print(file_full_name,file_name,folder)
        # print(desired_level_num)

        if not os.path.exists(f"{folder}/{file_name}_{desired_level}.json"):
            json_data = self.komaki_core.get_difficult_words(desired_level_num)
            with open(f"{folder}/{file_name}_{desired_level}.json","w") as file:
                json.dump(json_data,file,indent=2)
        with open(f"{folder}/{file_name}_{desired_level}.json","r") as f:
            self.dictionary = json.load(f)
        self.Main_bar.setValue(50)
        QTimer.singleShot(10, self.run_generate_button)

    def run_generate_button(self):
        if self.word_radio.isChecked():
            self.komaki_core.make_line_by_line(self.dictionary)

        if self.pdf_radio.isChecked():
            self.komaki_core.footer_font = self.footer_font.value()
            self.komaki_core.margin = self.margin.value()
            self.komaki_core.scale_factor_1 = self.scale_factor_1.value()
            self.komaki_core.scale_factor_2 = self.scale_factor_2.value()
            self.komaki_core.make_processed_pdf(self.dictionary)
        self.Main_bar.setValue(100)
        QMessageBox.information(self.Main_bar, "Finished", "Text processed successfully!")
            


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Komaki = QtWidgets.QDialog()
    ui = Ui_Komaki()
    ui.setupUi(Komaki)
    Komaki.show()
    sys.exit(app.exec_())
